### ISSUE TITLE
Pager library

### ISSUE THREAD

**Issue by loleg** [sacovo/public-transport-cli#1]
Currently the project doesn't build on Windows due to an issue in [pager](https://gitlab.com/imp/pager-rs/-/issues/5). It doesn't seem to be actively supported. For one line of code (almost), why not switch to https://github.com/Riey/rust-pager ?

**Comment by sacovo** [comment]
Thanks for the info, I decided to just remove the paging altogether, so everyone can decide to use some pager or not.
