### ISSUE TITLE
Escape sequences not working

### ISSUE THREAD

**Issue by pka** [sacovo/public-transport-cli#3]
Nice tool!

Escape sequences do not work on my machine.  Sample output:
```
ESC[1mSargans ⇒ Zürich HBESC[0m
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#1: 21:27 - 22:22, Leaves in  00:17

ESC[44;37m 21:27: Sargans                                         2   ESC[0m
ESC[36m   ┃  
ESC[0mESC[44;37m 22:22: Zürich HB                                       6   ESC[0m

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#2: 21:35 - 22:48, Leaves in  00:25

ESC[44;37m 21:35: Sargans                                         2   ESC[0m
ESC[36m   ┃  
ESC[0mESC[44;37m 22:48: Zürich HB                                       8   ESC[0m

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

No idea, whether it's a question of the console the shell or whatever...
I'm on Linux in a KDE konsole. Installed v0.1.2 with `cargo install`.

**Comment by sacovo** [comment]
I suspect this might be an issue with the pager. I removed paging in the latest version (0.1.3) that I just pushed to crates, does upgrading the package solve your issue? Otherwise you could try setting your `$PAGER` to `more` and see if that helps.

**Comment by pka** [comment]
In v0.1.4, the problem is solved, thanks!
